# File: Dockerfile.keycloak
FROM quay.io/keycloak/keycloak:24.0.3

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin

# Optional: Add realm or theme imports here
# COPY your-realm.json /opt/keycloak/data/import/

RUN /opt/keycloak/bin/kc.sh build

CMD ["/opt/keycloak/bin/kc.sh", "start-dev"]
