# Generated by Django 5.2 on 2025-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField()),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PROCESSING', 'Processing'), ('DELIVERED', 'delivered'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('order_details', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField()),
                ('created_by', models.UUIDField(default=models.UUIDField())),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='order_api_o_status_7a7ef4_idx'), models.Index(fields=['created_at'], name='order_api_o_created_66dc43_idx'), models.Index(fields=['customer_id', 'status'], name='order_api_o_custome_775c12_idx')],
            },
        ),
    ]
