# Generated by Django 5.2 on 2025-04-20 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('order_details', models.CharField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
