# Generated by Django 5.2 on 2025-04-17 00:22

import django.contrib.auth.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_alter_customer_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='roles_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KE'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='oidc_id',
            field=models.CharField(blank=True, help_text='OpenID Connect subject identifier', max_length=255, null=True, unique=True),
        ),
    ]
