# Generated by Django 5.2 on 2025-04-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0003_remove_customuser_roles_idx_remove_customuser_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
